version: '3.8'

services:
  eureka-server:
    build:
      context: ${EUREKA_SERVER_PATH}
      dockerfile: Dockerfile
    container_name: ${EUREKA_SERVER_CONTAINER_NAME}
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    networks:
      - shared_network

  song-service:
    build:
      context: ${SONG_SERVICE_PATH}
      dockerfile: Dockerfile
    depends_on:
      - song-db
      - eureka-server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SONG_CONTAINER_NAME: ${POSTGRES_SONG_CONTAINER_NAME}
      POSTGRES_SONG_DATABASE_PORT: ${POSTGRES_SONG_DATABASE_PORT}
      POSTGRES_SONG_DATABASE_NAME: ${POSTGRES_SONG_DATABASE_NAME}
    ports:
      - "${SONG_SERVICE_PORT_1}-${SONG_SERVICE_PORT_2}:${SONG_SERVICE_PORT_1}"
    deploy:
      replicas: 2
    networks:
      - shared_network

  song-db:
    image: postgres:alpine
    container_name: ${POSTGRES_SONG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_SONG_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: [ "postgres", "-p", "${POSTGRES_SONG_DATABASE_PORT}" ]
    ports:
      - "${POSTGRES_SONG_DATABASE_PORT}:${POSTGRES_SONG_DATABASE_PORT}"
    networks:
      - shared_network

  resource-service:
    build:
      context: ${RESOURCE_SERVICE_PATH}
      dockerfile: Dockerfile
    container_name: ${RESOURCE_SERVICE_CONTAINER_NAME}
    depends_on:
      - resource-db
      - song-service
      - eureka-server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SONG_SERVICE_HOST: http://microservices.song
      POSTGRES_RESOURCE_CONTAINER_NAME: ${POSTGRES_RESOURCE_CONTAINER_NAME}
      POSTGRES_RESOURCE_DATABASE_PORT: ${POSTGRES_RESOURCE_DATABASE_PORT}
      POSTGRES_RESOURCE_DATABASE_NAME: ${POSTGRES_RESOURCE_DATABASE_NAME}
    ports:
      - "${RESOURCE_SERVICE_PORT}:${RESOURCE_SERVICE_PORT}"
    networks:
      - shared_network

  resource-db:
    image: postgres:alpine
    container_name: ${POSTGRES_RESOURCE_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_RESOURCE_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-p", "${POSTGRES_RESOURCE_DATABASE_PORT}"]
    ports:
      - "${POSTGRES_RESOURCE_DATABASE_PORT}:${POSTGRES_RESOURCE_DATABASE_PORT}"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge