version: '3.8'

services:
  resourceapp:
    image: 'microservices.module1.resource:latest'
    build:
      context: .
    container_name: microservices.module1.resource.app
    depends_on:
      - resourcedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "8081:8081"
    networks:
      - shared_network

  resourcedb:
    image: postgres
    container_name: microservices.module1.resource.db
    environment:
      - POSTGRES_DB=resourcedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5433
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]
    networks:
      - shared_network

networks:
  shared_network:
    external: true