version: '3.8'

services:
  songapp:
    image: 'microservices.module1.song:latest'
    build:
      context: .
    container_name: microservices.module1.song.app
    depends_on:
      - songdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - shared_network

  songdb:
    image: postgres
    container_name: microservices.module1.song.db
    environment:
      - POSTGRES_DB=songdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - shared_network

networks:
  shared_network:
    external: true