spring:
  main:
    banner-mode: "off"
  application:
    name: microservices.song
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${POSTGRES_SONG_CONTAINER_NAME}:${POSTGRES_SONG_DATABASE_PORT}/${POSTGRES_SONG_DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  sql:
    init:
      mode: always
      platform: postgres

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

server:
  port: 8080
