spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            eureka-server:
              - uri: http://eureka-server:8761
  main:
    banner-mode: "off"
  application:
    name: microservices.song
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${POSTGRES_SONG_CONTAINER_NAME}:${POSTGRES_DATABASE_PORT}/${POSTGRES_SONG_DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
  sql:
    init:
      mode: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

server:
  port: 8080
