spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            eureka-server:
              - uri: http://eureka-server:8761
  main:
    banner-mode: "off"
  application:
    name: microservices.resource
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${POSTGRES_RESOURCE_CONTAINER_NAME}:${POSTGRES_RESOURCE_DATABASE_PORT}/${POSTGRES_RESOURCE_DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

client:
  song:
    host: ${SONG_SERVICE_HOST}
    saveSongMetadataPath: /songs
    getSongMetadataByIdPath: /songs/{id}
    deleteSongMetadataBulkPath: /songs

server:
  port: 8082
