spring:
  main:
    banner-mode: "off"
  application:
    name: microservices.module1.resource
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://microservices.module1.resource.db:5433/resourcedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  sql:
    init:
      mode: always
      platform: postgres

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

client:
  song:
    host: http://songapp
    port: 8080
    saveSongMetadataPath: /songs
    getSongMetadataByIdPath: /songs/{id}
    deleteSongMetadataBulkPath: /songs


server:
  port: 8081
