spring:
  main:
    banner-mode: "off"
  application:
    name: microservices.resource
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${POSTGRES_RESOURCE_CONTAINER_NAME}:${POSTGRES_RESOURCE_DATABASE_PORT}/${POSTGRES_RESOURCE_DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  sql:
    init:
      mode: always
      platform: postgres

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

client:
  song:
    host: http://song-service
    port: ${SONG_APP_PORT}
    saveSongMetadataPath: /songs
    getSongMetadataByIdPath: /songs/{id}
    deleteSongMetadataBulkPath: /songs

server:
  port: 8081
